[build]
    command = "pip install -r requirements.txt"


[phases.setup]
nixPkgs = [
  "python311",  # Версия Python, которую вы используете
  "libGL",      # Библиотека для работы с графикой
  "python3",      # Другие системные зависимости, если необходимы
  "ffmpeg",   # Эквивалент ffmpeg в Nix
  "libsm",    # Эквивалент libsm6
  "libxext"   # Эквивалент libxext6
]

[phases.build]
    commands = ["pip install -r requirements.txt"]
    output = "requirements.txt"