[build]
    command = "pip install -r requirements.txt"

[phases.setup]
    apt_pkgs = ["python3", "python3-pip", "libgl1-mesa-glx"]

[phases.build]
    commands = ["pip install -r requirements.txt"]
    output = "requirements.txt"